version: "3.8"

networks:
  nobolso-network:
    name: nobolso-network

services:
  host:
    build:
      context: .
      dockerfile: ./apps/host/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - TRANSACTIONS_URL=http://transactions:3001
      - DASHBOARD_URL=http://dashboard:3002
      - API_URL=http://api:8080/api
    depends_on:
      - transactions
      - dashboard
    networks:
      - nobolso-network

  transactions:
    build:
      context: .
      dockerfile: ./apps/transactions/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - API_URL=http://api:8080/api
    networks:
      - nobolso-network

  dashboard:
    build:
      context: .
      dockerfile: ./apps/dashboard/Dockerfile
    ports:
      - "3002:3002"
    environment:
      - API_URL=http://api:8080/api
    networks:
      - nobolso-network
